test: deploy
	@echo "Test stage deployment"

deploy: build
	@echo "Deploy application to stage server"

build: clean
	@echo "Build application"

clean:
	@echo "Clean up old files"

.PHONY: clean build deploy test